name: Publish Package to npmjs

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          registry-url: "https://registry.npmjs.org"
          scope: "@tf2pickup-org"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Install protoc
        uses: arduino/setup-protoc@v1

      - name: Generate proto files
        run: yarn generate-proto

      - name: Build
        run: yarn build

      - name: Publish
        run: yarn npm publish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
